### ISSUE TITLE
[Remote] Mid Full-stack Engineer. NET Strider 

### ISSUE THREAD

**Issue by Claudiaantunesdelima** [dotnetdevbr/vagas#1001]
#Mid Full-stack Engineer - .NET, React.js) 💰USD 3.5k /m(B2) 

https://app.onstrider.com/r/claudiaantunes?job=bWlkLWZ1bGwtc3RhY2stZW5naW5lZXItLm5ldC03ZDM1ODBiND9yZWZlcnJhbD1jbGF1ZGlhYW50dW5lcw==

**Comment by dynaput247** [comment]
Hello, I saw your job post and I am very interested.
I want to join your company.
toptalent48@gmail.com (gmail)
discord - username: MVP, id: 84478447
skype - live:.cid.b5e7c8f996fa441a

**Comment by jaime-junior-nutrien** [comment]
Job is closed

**Comment by jaimetjr** [comment]
Job is closed
