### ISSUE TITLE
[São Paulo] Senior Developer DotNet @ BANCO DAYCOVAL

### ISSUE THREAD

**Issue by mairaparanhos** [dotnetdevbr/vagas#129]
O Grupo Daycoval é formado por um time de pessoas engajadas e de bom astral. Todos imbuídos de fazer diferença nas vidas de nossos clientes. Sabemos o quanto o mercado financeiro é desafiador e de alta demanda – é disso que gostamos.
Nosso mercado está frenético com a entrada do mundo digital e por aqui atuamos em transformar nossos processos de forma ativa. Estamos cheios de desafios, então vem fazer parte deste time!

DESCRIÇÃO DA VAGA

Atuar com desenvolvimento/arquitetura, testes e documentações de features de inovação e manutenção dos produtos.
Trabalhar em equipe, buscar sempre atualização e compartilhar conhecimento.
Pro ativo na busca de conhecimento e atualizações. Perfil que esteja engajado com a melhoria da área.

Local: Avenida Paulista, São Paulo, SP

RESPONSABILIDADES E ATRIBUIÇÕES
Desenvolver sistemas;
Analisar/Buscar soluções;
Acompanhar backlog, monitoramento de projetos/chamados;
Desenvolver e implantar projetos/ melhorias;
Documentar processos e soluções;
Participar de reuniões com usuários das áreas de negócio;
Definir padrões para outros desenvolvedores.
REQUISITOS E QUALIFICAÇÕES
Graduação na área de TI;
Linguagem .Net(C# e/ou VB.NET);
HTML5, CSS3 e Jquery;
Front-end Web (Angular, Bootstrap, WebForms);
Banco de Dados Relacionais (SQL Server).

Conhecimento em:
NET Core (C#);
Construção e manutenção de APIs (SOAP / RESTful).

Benefícios
•   Assistência Médica e Assistência Odontológica;
•   Vale-refeição e Vale-alimentação;
•   Refeitório;
•   Auxílio-creche;
•   Seguro de Vida;
•   Vale-transporte;
•   Previdência Privada;
•   Participação nos Lucros ou Resultados;
•   Programa de Participação de Resultados;
•   Apoio à Educação;
•   Serviço Social;
•   Ginástica laboral;
•   Parcerias com desconto.

## Contratação
CLT Full time

## Como se candidatar
https://bancodaycoval.gupy.io/jobs/533526

**Comment by FilipeAugustoVO** [comment]
Com licença, por que a empresa precisa do meu RG, nome do meu pai e nome da
minha mãe para cadastrar em alguma vaga? Não tem a mínima necessidade
disso. Isso me parece profundamente suspeito e inapropriado para uma
empresa requisitar.

**Comment by mairaparanhos** [comment]
Olá @FilipeAugustoVO

Em resposta à sua pergunta sobre dados cadastrais, essa etapa faz parte do nosso processo seletivo para que possamos cadastrar os candidatos com as informações completas em nossa plataforma , possibilitando avaliação correta sem considerar homônimos e inclusão de candidatos fantasmas ou falsos.

Ficamos à disposição,
BANCO DAYCOVAL
