### ISSUE TITLE
[Cidade ou Remoto] Back-end Developer DotNet @Oficina de Talentos

### ISSUE THREAD

**Issue by oficinadetalentos** [dotnetdevbr/vagas#237]
Desenvolvimento de teste softwares, preparar documentação, realizar manutenções no sistema. Time 18 profissionais (Desenvolvedores, Analista de Negócios e Analista de Testes). 
Análise e Desenvolvimento web em C# (recebe e desenvolve o projeto front e back end), Java, Banco de Dados (SQL Server) Desejável conhecimento em Entity, Vue.JS, legado ASP.Net e VB.Net.
A empresa é de grande porte e possui mais de 5 mil funcionários e presta serviço para instituições financeiras, é uma empresa que possui plano de carreira. 
Localização próx ponte do Limão / Centro de Tradições, porém devido ao cenário pandêmico, todos estão trabalhando de forma remota. 
Benefícios: AM - Amil Blue 600, AO, VR+VA, SV, VT.

**Comment by CarlosHenriqueRC** [comment]
Caros,

E após a pandemia, o trabalho pode continuar remoto ou não ?
******************************************
*Carlos Henrique Ramos Carvalho
*Especialista em Tecnologia .Net
*MCP.Net
******************************************


Em sex., 23 de abr. de 2021 às 14:47, oficinadetalentos <
***@***.***> escreveu:

**Comment by oficinadetalentos** [comment]
Olá! Como vai?

 

Carlos Henrique, 

 

Neste momento de pandemia, a vaga é 100% home office.

 

Caso tenha interesse em conversar conosco, por gentileza me passe seu número de WhatsApp... o meu é (11) 99353-1206.

 

À disposição,

 

Atenciosamente,

Elisângela Sousa 

Consultora de RH

Oficina de Talentos Consultoria RH

Telefone: (11) 3892-9982    (11) 99353-1206



 

            <https://pt.linkedin.com/company/oficina-de-talentos---consultoria-em-rh>      <https://pt-br.facebook.com/oficinatalentosrh/>      <https://www.oficinatalentos.com.br/>      <https://www.instagram.com/oficinatalentosrh/?hl=pt> 

 

De: CarlosHenriqueRC ***@***.***> 
Enviada em: sexta-feira, 23 de abril de 2021 15:41
Para: dotnetdevbr/vagas ***@***.***>
Cc: oficinadetalentos ***@***.***>; Author ***@***.***>
Assunto: Re: [dotnetdevbr/vagas] [Cidade ou Remoto] Back-end Developer DotNet @Oficina de Talentos (#237)

 

Caros,

E após a pandemia, o trabalho pode continuar remoto ou não ?
******************************************
*Carlos Henrique Ramos Carvalho
*Especialista em Tecnologia .Net
*MCP.Net
******************************************


Em sex., 23 de abr. de 2021 às 14:47, oficinadetalentos <
***@***.***> escreveu:

**Comment by CarlosHenriqueRC** [comment]
E depois passará a ser presencial ?

Em seg, 26 de abr de 2021 15:47, oficinadetalentos ***@***.***>
escreveu:

**Comment by oficinadetalentos** [comment]
Boa noite!

 

Ainda não tive esta resposta...

 

Atenciosamente,

Elisângela Sousa 

Consultora de RH

Oficina de Talentos Consultoria RH

Telefone: (11) 3892-9982    (11) 99353-1206



 

            <https://pt.linkedin.com/company/oficina-de-talentos---consultoria-em-rh>      <https://pt-br.facebook.com/oficinatalentosrh/>      <https://www.oficinatalentos.com.br/>      <https://www.instagram.com/oficinatalentosrh/?hl=pt> 

 

De: CarlosHenriqueRC ***@***.***> 
Enviada em: segunda-feira, 26 de abril de 2021 16:35
Para: dotnetdevbr/vagas ***@***.***>
Cc: oficinadetalentos ***@***.***>; Author ***@***.***>
Assunto: Re: [dotnetdevbr/vagas] [Cidade ou Remoto] Back-end Developer DotNet @Oficina de Talentos (#237)

 

E depois passará a ser presencial ?

Em seg, 26 de abr de 2021 15:47, oficinadetalentos ***@***.***>
escreveu:
