### ISSUE TITLE
[.NET CORE] [Valinhos SP/REMOTO] [KROTON] [https://byintera.in/dtntbr]

### ISSUE THREAD

**Issue by izabellaschafhauser** [dotnetdevbr/vagas#265]
O que acha de fazer parte de uma empresa que tem investido fortemente em tecnologia?

A Kroton está passando por um forte processo de transformação cultural e digital e planeja ser o maior grupo de edtechs do Brasil. Para isso, está construindo um time de tecnologia de alto nível e busca pessoas que desenvolvam em .NET Core para fazer parte da equipe e impactar a vida de milhões!

Como integrante de um time ágil de desenvolvimento, você terá desafios técnicos, participará ativamente dos ritos Scrum (Planning, Daily Meeting, Review e Retro), oportunidade em que será responsável pelo planejamento e entrega de produtos que estão em evolução para novas arquiteturas.

É um ambiente colaborativo e o dress code é liberado!

Acha que fez sentindo pra você? Ou conhece alguém que está buscando essa oportunidade?

Dá uma olhadinha na vaga então e, se curtir, é só se inscrever! Caso esteja interessado, mas queira saber mais detalhes, fala comigo que eu estou 100% disponível para te ajudar. 

[ https://byintera.in/dtntbr ]

**Comment by guibranco** [comment]
@izabellaschafhauser  por favor respeitar o template de vagas.
Informar senioridade (JR, PL, SR), tipo de contratação (CLT, PJ, Freelancer, Cooperado), alocação (presencial, remoto, remoto covid-19) e dedicação (fulltime / part-time)
