### ISSUE TITLE
Remoto - Pessoa desenvolvedora .NET - DQR Tech

### ISSUE THREAD

**Issue by DaianeMFirmiano** [dotnetdevbr/vagas#401]
DQR TECH: Nascemos de uma parceria de mais de 10 anos entre seus sócios, somando a paixão por tecnologia à vontade de construir uma empresa diferente, investindo na proximidade com nossos parceiros e clientes. Somos uma consultoria especializada em Arquitetura de TI, Outsourcing de Profissionais e Hunting.  

DESAFIO: 
A DQR TECH está em busca de um profissional para atuar em Squad ágil no maior banco de Investimentos da América Latina.

CONTRATAÇÃO: 
CLT 100% Home Office

HARD SKILLS: 
Experiência em projetos de desenvolvimento de software utilizando .NET Framework, .NET Core e React/Angular;
Experiência em serviço de mensageria RabbitMQ/Kafka;
Design Patterns GoF;
Experiência em Modelagem de dados em DDD;
Desenvolvimento de aplicações em nuvem AWS, utilizando os serviços: Lambda, Sqs, DynamoDb, S3, EC2, RDS;

DIFERENCIAIS: 
Conhecimento de arquitetura em Microserviços;
Conhecimento em ferramentas de automação de infraestrutura as a code Jenkins;
Execução de Testes Unitários;
Metodologia ágil;

BENEFÍCIOS:
880,00 que podem ser distribuídos em VA e/ou VR (você decide a melhor forma de distribuição);
Plano de Saúde e Odontológico sem coparticipação;
Acesso aos cursos da plataforma Alura.
Premiação de R$ 1.000,00 para cada indicação aprovada.
Notebook para o desempenho das atividades.

**Comment by supercoja** [comment]
Boa tarde Daiane, tudo bem? Espero que sim!

Como funciona o processo de aplicação à vaga? 

Desde já agradeço, 

Muito obrigado!

Um abraço e até logo

**Comment by DaianeMFirmiano** [comment]
Olá, Thiago!!

Por gentileza, envie seu currículo para ***@***.***, que
faremos contato na Segunda!

Fique à vontade para me adicionar no LinkedIn também:
https://www.linkedin.com/in/daiane-firmiano-74b1a622

Fico a disposição!!
Abraço!!



Em qui., 29 de jul. de 2021 13:42, Thiago ***@***.***>
escreveu:
