### ISSUE TITLE
[Remoto] Fullstack .NET Core @ Wiz Soluções

### ISSUE THREAD

**Issue by IzabelleTR** [dotnetdevbr/vagas#459]
## Nossa empresa

Fazemos a distribuição de serviços financeiros e de seguros através da nossa plataforma multicanal. Transformamos dados em conhecimento e conectamos pessoas a empresas, oportunidades a necessidades, para potencializar negócios. Ao longo dos mais de 40 anos de atuação, desenvolvemos e implementamos plataformas integradas de relacionamento e venda, garantindo agilidade e presença em todo território nacional.

## Local

Remoto.

## Requisitos

**Obrigatórios:**
- Experiência com .NET Core;
- Experiência com Angular, React ou Node. 

**Desejáveis:**
- Experiência com Azure.

## Contratação

CLT. 

## Como se candidatar

Candidate-se na nossa plataforma: https://jobs.kenoby.com/wiz/job/desenvolvedora-fullstack-brasil/60d22d0abb476858c3bda292?utm_source=website

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Júnior
- Pleno

#### Período
- Full time

**Comment by arielfontes15** [comment]
![image](https://user-images.githubusercontent.com/72883707/133448794-cfdd45ec-0073-4198-b3a3-16038162dfcf.png)
