### ISSUE TITLE
[Remote - Europe] Full Stack Developer DotNet @ DREAMDEV

### ISSUE THREAD

**Issue by talita-moura** [dotnetdevbr/vagas#554]
## Nossa empresa

DREAMDEV is a European Software Consultancy company, built-in 2018 and based in Ireland.
We have large-scale projects with eCommerce, Financial Services, Real State, and Telecom companies across the EU and UK and we provide them cross-functional, self-organizing, agile teams located either on-site, off-site, or offshore.

Learn more at https://dreamdev.io/ or https://www.linkedin.com/company/dreamdevio/

## Descrição da vaga

We are looking for Mid-Level and Senior Engineers with knowledge in building high performance, low latency, multi-threaded dotnet microservices.

The person will have the opportunity to work in distributed teams across Europe

## Local

Full remote.

## Requisitos

**Obrigatórios:**
- C# (At least 4 years of experience) 
- B2 - Upper-intermediate English (able to interview and communicate)

**Desejáveis:**
-  Azure
- Working experience using TDD, DDD and CQRS 

## Contratação

PJ - salary range starting at 170€/day (about 3500€ per month)

## Como se candidatar

Please, send me an email at talita.nardo@dreamdev.io with your resume attached with the title "Dotnet - GitHub"

## Tempo médio de processo e feedbacks

Our process usually takes 1 pre-screening and 3 interviews.
We expect to send you the feedback in 7 working days after each step of the interview.
If you don't have any questions, feel free to reach me out at: talita.nardo@dreamdev.io

#### Alocação
- Remoto
- Offshore

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

#### Período
- Full time

**Comment by luicesar** [comment]
Boa noite, o inglês precisa ser fluente ?
