### ISSUE TITLE
[Remoto] Back-end Developer DotNet @Stefanini

### ISSUE THREAD

**Issue by JessicaMayala** [dotnetdevbr/vagas#573]
## Nossa empresa

Somos a maior multinacional brasileira e estamos entre as 100 maiores empresas no mundo no ramo de TI 💻, presente em 41 países com +25k colaboradores global 🌎

Visamos sempre o nosso objetivo de co-criar soluções para um futuro melhor e acreditamos no respeito, nos princípios éticos e íntegros, assim como, na humildade em aprender!

É importante ressaltar o respeito a diversidade, pois entendemos que as diferenças tornam as pessoas únicas, por isso, não fazemos qualquer distinção entre nossos candidatos. Para nós, não importa idade, gênero, raça/etnia, deficiência, orientação sexual, origem, estética ou constituição familiar. 

Acreditamos no potencial dos nossos colaboradores! ✨
Se identificou? Então venha para a Stefanini, nós estamos ansiosos para te conhecer! 🤩

## Descrição da vaga

Fará parte do time Stefanini integrado com o cliente, uma multinacional americana, atuando na sustentação de sistemas legados e criação de novas funcionalidades .

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Net Core
- Net Framework 3.0 a 4.5
- Angular
- Webforms

**Desejáveis:**
- CSS3;
- MVC 4 Web Applications;
- ASP .Net
- PL/SQL
- Microsoft Visual Studio e IIS Manager 

## Benefícios

- VR/VA 
- Plano de saúde  – Coparticipativo (valores abaixo)
- Plano Odontológico Odontroprev
- Parceria com Sesc 
- Seguro de Vida anual gratuito
- Auxílio Funeral
- Gympass
- Programa de orientação psicológica, financeira e jurídica gratuito para colaboradores e dependentes legais
- Go Integro (clube de descontos nos melhores estabelecimentos da América Latina)
- Allpoints (Plataforma de moeda de viagens)
- Convênio de desconto com universidades e escolas de inglês
- Empréstimo consignado junto ao banco da folha de pagamento
- Incentivo a atualização e desenvolvimento profissional:
Trilha de carreiras na Academia Stefanini
Programa de mentoria
50% reembolso certificação em caso de aprovação
Plataforma Career (Recrutamento Interno) 
Descontos Alura

## Contratação

CLT

## Como se candidatar

Pela nossa página https://lnkd.in/eUY6xHsu

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Júnior
- Pleno
- Sênior

#### Período
- Full time

**Comment by luicesar** [comment]
Bom dia, a vaga está aberta ainda ?

**Comment by guibranco** [comment]
> Bom dia, a vaga está aberta ainda ?

Acredito que esteja, veja por este link: https://jobs.kenoby.com/vagasstefanini/job/dev-net-pleno/61e5be7a01c09f0b26694ba6?utm_source=website
