### ISSUE TITLE
[Remoto] Pessoa Desenvolvedora .Net (Júnior, Pleno e Sênior) na Cielo 

### ISSUE THREAD

**Issue by talissoncarv** [dotnetdevbr/vagas#597]
## Nossa empresa

A Cielo está para todas as pessoas, assim como o #TimeCielo está para a inclusão. Esse é nosso lema, essa é nossa missão! Somos apaixonados por tecnologia e buscamos sempre colocar o cliente no centro de nossas ações. São mais de 25 anos fazendo história ao lado de quem faz um negócio acontecer no Brasil e na América Latina. São mais de 1,4 milhões de clientes e cada um deles importa.

## Descrição da vaga

Procuramos por Pessoas Desenvolvedoras .Net (Júnior, Pleno e Sênior), para atuar com o back-end de nossos produtos transacionais, tendo como foco manutenção e evolução de soluções de alta performance e criticidade.

## Local

Remoto

## Requisitos

**Obrigatórios:** (varia a depender da senioridade, acesse o link e saiba mais: https://bit.ly/3sFKKvx ) 

- Experiência como desenvolvedor .Net;
- Vivência sobre ASP .Net Core;
- Experiência com tecnologia SQL e bancos relacionais;
- Vivência com metodologia ágil de desenvolvimento (Kanban/Scrum);
- Conhecimentos e vivência sobre arquitetura API REST;
- Conhecimentos e vivência sobre frameworks/injeção de dependências;
- Conhecimentos e vivência sobre testes automatizados/testes unitários/TDD
- Conhecimentos e vivência sobre Plataforma Cloud (Azure);
- Conhecimentos e vivência sobre Code Design;
- SOLID/Design Patterns/DDD.

## Benefícios

- Vale Refeição
- Vale Alimentação
- Vale Transporte
- Estacionamento
- Assistência Médica
- Assistência Odontológica
- Seguro de Vida
- Gympass
- PLR / Stock Options
- Licença maternidade e paternidade estendida
- Auxílio Creche
- No dresscode
- Política de Home Office
- Auxílio Deslocamento
- Previdência Privada
- Atendimento de Especialidades Médicas
- Vacina contra Gripe
- Sexta mais curta

## Contratação

CLT

## Como se candidatar

Saiba mais e candidate-se em: https://bit.ly/3sFKKvx

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Júnior
- Pleno
- Sênior

#### Período
- Full time

**Comment by luizfernandonb** [comment]
Essa vaga ainda está aberta?
