### ISSUE TITLE
[Remoto] Analista Programador(a) ASP MVC Core Web API @ Copastur 

### ISSUE THREAD

**Issue by larissazz** [dotnetdevbr/vagas#636]
VAGA REABERTA! Já contratamos 3 candidatos e estamos contratando + 2! 

## Nossa empresa

Venha trabalhar na Copastur, empresa que possui mais de 45 anos de história e é referência no segmento do turismo. A Copastur é GPTW (Great Place to Work), certificada pela ISO 9001 e ISO 14001 (única empresa do segmento que conta com o certificado)! Apesar da pandemia a empresa não teve dificuldades onde não demitiu ou reduziu custos, pelo contrário, ainda tendo muito lucro e fazendo contratações por ser uma área de viagens e turismo principalmente executiva e de negócios.

## Descrição da vaga

Você irá trabalhar no time com o desenvolvimento dos sistemas da empresa.

Responsabilidades:

-Desenvolver e criar testes unitários;
-Realizar levantamento de requisitos com o cliente final (interno ou externo);
-Propor arquitetura/design dos sistemas;
-Levantamento de requisitos de desenvolvimento de software, com clientes internos e externos;
-Documentar sistemas novos e/ou já existentes;
-Refatorar sistemas para facilidade de manutenção.

## Local

-Remoto.

## Requisitos

**Obrigatórios:**
-Net Core, Net Framework, ASP.NET MVC, Net Web API;
-Experiência em desenvolvimento/programação de softwares.

**Desejáveis:**
-Metodologia ágil;
-Rest/WCF;
-SOA, BDD, SSO;
-AngularJS, React;
-SOLID, DDD, DRY, KISS e YAGNI.

## Benefícios
-VR - para todo mundo se alimentar bem!
-Plano de saúde - Bradesco;
-Plano odontológico - Bradesco;
-Seguro de Vida - Zurich;
-GymPass - movimente-se!
-Allura - para você se desenvolver estudando;
-Allya - descontos diversos para o seu salário render mais;
-Apoio Pass - suportes diversos ao colaborador;

**Diferenciais:**
-Mindfulness - começando o dia bem com meditação;
-Ginástica laboral - nos alongamos com música e diversão;
-Licença Paternidade - para aquele que se torna papai, 30 dias em casa com seu(sua) filho(a).

## Contratação

-PJ full time ou CLT.

## Como se candidatar

Saiba mais e se candidate no site (basta fazer login, inserir seus contatos e se candidatar): https://vagas.hunterco.com.br/job/62682b3063d540001e8d9dfc?c=4740

## Tempo médio de feedbacks

Para cada etapa o prazo de retorno é de +- 5 dias úteis. Após se candidatar no site, a Recrutadora irá entrar em contato com você para alinhamento ou feedback negativo (pode ser pelo E-mail, LinkedIn ou WhatsApp). 

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior

#### Período
- Full time

**Comment by larissabazzo** [comment]
Vaga aberta ainda! :)

**Comment by larissabazzo** [comment]
vaga aberta!

**Comment by larissabazzo** [comment]
Vaga aberta ainda!

**Comment by larissabazzo** [comment]
Vaga temporariamente inativa!
