### ISSUE TITLE
[Oportunidade Remoto] FULLSTACK .NET  DQR TECH 

### ISSUE THREAD

**Issue by carolinetech** [dotnetdevbr/vagas#663]
## SOBRE NÓS
Nascemos de uma parceria de mais de 10 anos entre seus sócios, somando a paixão por tecnologia à vontade de construir uma empresa diferente, investindo na proximidade com nossos parceiros e clientes. Somos uma consultoria especializada em Arquitetura de TI, Outsourcing de Profissionais e Hunting.

## DESAFIO:
A DQR TECH está em busca de um profissional para atuar em Squad ágil no maior banco de Investimentos da América Latina.

## REQUISITOS:
Experiência em projetos de desenvolvimento de software utilizando .NET Framework, .NET Core e React/Angular;
Experiência em serviço de mensageria (RabbitMQ/Kafka, ou semelhante);
Design Patterns GoF;
Desenvolvimento de aplicações em nuvem AWS, utilizando os serviços: Lambda, Sqs, DynamoDb, S3, EC2, RDS;

## DIFERENCIAL:
Experiência em Modelagem de dados em DDD;
Conhecimento de arquitetura em Microserviços;
Conhecimento em ferramentas de automação de infraestrutura as a code Jenkins;
Execução de Testes Unitários;
Metodologia ágil;

## Benefícios
Vale Refeição/Alimentação;
Assistência médica e Odontológica;
Seguro de Vida;
Acreditamos no desenvolvimento contínuo de nossos colaboradores,
dessa forma oferecemos acesso full aos cursos da plataforma ALURA;
Auxílio-creche;
No seu aniversário tem mimos;

Por favor envie um email para caroline.silva@dqrtevch.com.br com seu CV anexado - enviar no assunto: Vaga DotNet

**Comment by gsabreudev** [comment]
#vem pra Dqr tech!
