### ISSUE TITLE
[São Paulo com possibilidade Remota] Arquiteto de Soluções . Net @DBSP @remotonapandemia @arquiteto

### ISSUE THREAD

**Issue by Simonedantas** [dotnetdevbr/vagas#71]
O que vamos construir juntos?

A oportunidade é para atuar uma solução bancária distribuída globalmente. Você trabalhará com Arquitetura criando recursos transversais e colaborando com práticas e padrões que serão aplicados em todos as Squads.

**Requisitos para se candidatar a vaga**:

Experiência como mentor de equipes de desenvolvimento e experiência comprovada em escrever código de produção em .NET Core, Java ou C# para uma empresa de software comercial;
Experiência com tomada de decisão sobre arquitetura e design; como modelagem de domínio, aplicação de padrões de design e design usando componentes de terceiros;
Conhecimento de API First Design;
Experiência em projetos de paradigmas de computação em nuvem (como Amazon Web Services, Azure ou Google Cloud Platform);
Experiência em sistemas de grande escala, tendo lidado com dados / transações / eventos de alto rendimento;
Sólidos conhecimentos em microsserviços;
Sólidos conhecimentos de CI / CD e Git;
Experiência em trabalhar com containers e orquestradores de container;
A capacidade de simplificar ideias complexas e comunicá-las com pensamento lógico e claro;
Capacidade demonstrada de trabalhar colaborativamente dentro da equipe e com outras partes da organização;

**Atividades:** 
Atuação com metodologias ágeis;
Microsserviços horizontalmente escaláveis ​​escritos principalmente em .net core e Java;
Arquitetura limpa / hexagonal;
Trabalhos de alto rendimento e comunicação entre serviços usando Kafka;
Integração e implantação contínuas no Azure;
Monitoramento e observabilidade com Prometheus e Grafana;
Execução de Kubernetes;

 Por aqui você terá:
Vale Refeição;
Vale Transporte (Não se aplica no período de pandemia, já que estamos trabalhando de home- office)
Plano de Saúde & Odontológico Sulamerica;
Subsidio para o home-office;
Horário flexível;
Dresscode: seja você.

**Diversidade**
Acolhemos a diversidade. Tratamos a todos indistintamente e não toleramos preconceito e discriminação em qualquer relação com o nosso público, sejam clientes, fornecedores, prestadores ou colaboradores.

**Como se candidatar:**
encaminhe cv para simone.santos@dbsp.pro ou 
pelo link https://jobs.kenoby.com/dbsp/job/pessoa-arquiteta-net/5f7f2d1022f6432a3b1c7ffd
#VEMPRADBSP

**Comment by guibranco** [comment]
@Simonedantas  por favor, edite o issue, adicionando informações da vaga, como forma de contratação (CLT, PJ), disponibilidade (fulltime, part-time), nível esperado do candidato (júnior, pleno, sênior), e local de atuação (alocado, remoto, remoto durante pandemia apenas).
