### ISSUE TITLE
[Remoto] Dev. .Net Pleno PITANG

### ISSUE THREAD

**Issue by Luanadsl** [dotnetdevbr/vagas#73]
## Nossa empresa

Estamos há 16 anos no mercado desenvolvendo projetos de transformação digital. Nosso foco é desenvolvimento de software sobre demanda.
Spinoff da área de projetos do CESAR, hoje temos em média 400 colaboradores em diversas regiões do pais para atender clientes de médio e grande porte nos setores privados e públicos. Somos uma empresa certificada pelo Great Place To Work.

## Descrição da vaga
Nível Pleno - Oportunidade CLT 40h semanais - REMOTO (100% Home office)
Atuar como desenvolvedor em um projeto técnico de desacoplamento de base e
modernização de arquitetura. .Net Framework e Core Web Forms e MVC Web Services, WCF e WebApi JWT Testes
Unitários SqlServer

#REMOTO

## Requisitos

**Obrigatórios:**
.Net Framework e Core Web Forms e MVC Web Services, WCF e WebApi JWT Testes
Unitários SqlServer

## Benefícios
- Plano de saúde
- Plano Odontológico
- VR 
- Auxílio creche

**Comment by guibranco** [comment]
@Luanadsl  por favor, edite o issue, adicionando informações da vaga, como forma de contratação (CLT, PJ), disponibilidade (fulltime, part-time), nível esperado do candidato (júnior, pleno, sênior), e local de atuação (alocado, remoto, remoto durante pandemia apenas).
