### ISSUE TITLE
[Curitiba] Tech Lead .NET @uCondo

### ISSUE THREAD

**Issue by NatachaNarimatsu** [dotnetdevbr/vagas#786]
### Nossa empresa

A oportunidade é para a empresa **uCondo**, é uma startup com um sonho grande: tornar todos os condomínios inteligentes! A **uCondo** existe porque a comunicação dos condomínios é precária e desorganizada, administradoras de condomínios possuem processos burocráticos, caros e demorados. Nosso propósito é proporcionar economia e comodidade para administradoras, pessoas síndicas e moradoras, nos tornando assim, o melhor App de condomínios das Américas! 💜

### Descrição da vaga

- Definir junto ao time técnico os melhores caminhos para a construção da solução;
- Puxar todas as rotinas do SCRUM da sua Squad;
- Ser especialista do negócio e interagir com o Product Owner na definição dos requisitos trazendo sempre uma visão técnica de viabilidade e tempo estimado de desenvolvimento;
- Quando necessário, participar da criação ou correção das funcionalidades;
- Prestar suporte do produto aos demais times da empresa;
- Apoiar a definição, gestão do Roadmap e das sprints;
- Testar funcionalidades implementadas antes do lançamento (feature review);
- Aprovar junto com o Product Owner da squad a liberação dos itens desenvolvidos para o ambiente de produção;
- Gerenciar o time de Devs da sua squad, conduzindo agendas de 1:1s, feedbacks e apoiando no desenvolvimento da carreira dos programadores;
- Trabalhar com o time de Pessoas para realizar recrutamento, seleção, integração e treinamento dos novos Devs das squads;
- Validar documentações técnicas de itens desenvolvidos e orientar o time nessa construção.

### Local

**100% remoto**

### Requisitos

**#### Requisitos:**

- Sólida experiência em desenvolvimento de aplicações .NET C# (nível sênior é obrigatório);
- Experiência em gestão de pessoas;
- Sólidos conhecimento em métodos ágeis (SCRUM);
- Sólida experiência em arquitetura de aplicações;
- Excelente capacidade de comunicação e escrita;
- Vivência em boas práticas de software como Clean Code, Clean Architecture, etc
- Transmitir as necessidades da equipe aos líderes da empresa;

**### Desejáveis:**

- Configuração de ambientes em nuvem AWS;
- Experiência em CloudFlare;
- Vivência no ramo condominial, e/ou empresas de tecnologia, ERPs, fintechs ou startups SaaS;
- Vivência em implantação de esteiras CI/CD com o AWS CodeBuild, ECR, ECS;
- Conhecimentos em Git, SQL Server, Redis, SQS e S3;
- Conhecimentos em outras tecnologias como Swift, Kotlin, C#, Java, etc.

### Benefícios

🍔 VA da Flash de R$ 484,00 por mês sem descontos!
💻 Equipamentos e auxílio Home Office de R$50,00 por mês
🩺 Plano de Saúde Bradesco Nacional sem desconto!
😁 Plano Odontológico Bradesco sem desconto!
💜 Seguro de Vida sem coparticipação!
🚀 Treinamento, cultura de 1:1s e plano de carreira

### Contratação

CLT

### Como se candidatar

Por favor envie um e-mail para talentos@ucondo.com.br com seu currículo em anexo e com o título da vaga no assunto

### Keywords

.net, C#, 

### Alocação

- [ ] Alocado
- [X] Remoto
- [ ] Presencial
- [ ] Híbrido

### Regime

- [X] CLT
- [ ] Estágio
- [ ] Freela
- [ ] PJ

### Nível

- [ ] Júnior
- [ ] Pleno
- [X] Sênior
- [X] Especialista

### Período

- [X] Full time
- [ ] Part Time
- [ ] Projeto

**Comment by guibranco** [comment]
@NatachaNarimatsu você queria mesmo fechar essa vaga ?

**Comment by NatachaNarimatsu** [comment]
> @NatachaNarimatsu você queria mesmo fechar essa vaga ?

Claro @guibranco 🤩

**Comment by guibranco** [comment]
É porque ela tinha acabo de ser aberta, achei que tinha sido engano, então tudo bem =D

**Comment by NatachaNarimatsu** [comment]
Pode ser que eu tenha me enganado, sou nova postando as vagas aqui no git kkk
Poderia me dar uma ajuda? A vaga está aberta para você?

**Comment by NatachaNarimatsu** [comment]
Muito obrigada @guibranco 🙏😊

**Comment by guibranco** [comment]
Não, a vaga está fechada (você clicou em "clouse issue", eu vou reabrir a vaga.
