### ISSUE TITLE
Home office ou semipresencial em Colombo/PR  Back-end Developer .NET Júnior @ BNE (Banco Nacional de Empregos)

### ISSUE THREAD

**Issue by israelaandrade** [dotnetdevbr/vagas#839]
## Nossa empresa

Aqui no BNE a natureza é de tecnologia e inovação, somos uma empresa de tecnologia com enfoque em RH.

## Descrição da vaga

O profissional atuará na criação e aplicações web, em projetos de alta de manutenção no cenário nacional.

## Local

Remoto ou semipresencial em Colombo/PR.

## Requisitos

**Obrigatórios:**
- Conhecimentos júnior C# [ASP.NET](https://asp.net/) CORE
- Conhecimentos júnior de MVC
- Servidor SQL

**Desejáveis:**
- Conhecimentos em processos assíncronos
- Desenvolvimento de sistemas em nuvem (Azure)
- SCRUM
- Angular
- Servidor de identidade

**Diferenciais:**
- Quarta do CS, onde os devs se reúnem após o serviço para jogar CS e interagirem.
- Tecnologias recentes do mercado
- Oportunidades de crescimento
- Oportunidades de reconhecimentos

## Contratação

PJ a combinar.

## Como se candidatar

Por favor envie uma mensagem pelo WhatsApp, enviar no assunto: Vaga Back end (GitHub) através de nosso Linktree: https://linktr.ee/ia_vagaserecrutamento

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
Contato em caso de não haver resposta: Por favor envie um email para: [israelaandrade@bne.com.br] com seu CV anexado - enviar no assunto: Vaga Back end (GitHub)

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior

**Comment by rodrigues-i** [comment]
O link para o  Linktree e nem tampouco o e-mail disponibilizado estão funcionando.
De qualquer forma, eu queria me candidatar. Este é o meu github e na descrição do meu perfil há um link para o meu perfil no linkedin.
