### ISSUE TITLE
[São Paulo - Híbrido] Full Stack Developer PL/SR @Tecnologia Única 

### ISSUE THREAD

**Issue by marinasgriza1993** [dotnetdevbr/vagas#858]
> Venha fazer parte de uma empresa que acredita e aposta em novas ideias, com um time 
> forte, e com propósito que já soma mais de 200 pessoas.

 Somos uma empresa de desenvolvimento de sistemas fundada em 2004. Nossas principais 
soluções são para o mercado segurador e de fidelização para diversos segmentos, desde o 
varejo até o agronegócio. Também mantemos um ecossistema de startups, nosso pilar de 
inovação. Parceira de grandes players de mercado de tecnologia, entre eles Microsoft e 
AWS, temos a missão de impactar a vida das pessoas provendo soluções disruptivas, 
investindo massivamente em nosso time, sempre perseguindo e incentivando processos 
criativos.

Sentiu a energia única e se identificou com o nosso propósito?
**#VemSerUnico**

**O que você fará:**
 Desenvolvimento e manutenção de aplicações web;
 Desenvolvimento de funcionalidades no Front-End;
 Desenvolvimento de funcionalidades no Back-End;
Para esta vaga você precisa ter:
 Formação em Tecnologia;
 Conhecimento em metodologias ágeis (Scrum/Kanban);
 Experiência em .NET, C#, ASP.NET, APIS REST/JSON;
 02 + anos de experiência com plataforma Microsoft SQL;
 Conhecimento de JavaScript, CSS, HTML para criação de Front-ends Web;
 Conhecimento em Arquitetura MVC;
 GIT;

**Para esta vaga seria ótimo se você tivesse:**
 Conhecimento em React.js;
 Experiência em microsserviços.

**Contratação:**
Regime PJ + Auxílios + Gympass + Apoio psicológico (Psicologia Viva) + Day Off 
Remunerado no Aniversário + Dias de Descanso Remunerado + Bônus para Certificação;
Local de trabalho: 100% Home Office **(Híbrido nos 2 primeiros meses - 1x por semana) - São Paulo, SP.**

_Aqui na única você pode ser quem é verdadeiramente, pois temos como premissa respeitar 
e valorizar as diferenças. Somos diversos e buscamos criar um ambiente cada vez mais 
inclusivo_

Caso tenha interesse na oportunidade, é só me procurar através do email: [mgriza@tecnologia-unica.com.br]

**Comment by marinasgriza1993** [comment]
Ainda temos vagas abertas pessoal!

**Comment by MauroFausto** [comment]
Bom dia, essa vaga ainda está aberta?

**Comment by marinasgriza1993** [comment]
Boa tarde
Sim, ainda está disponível!
Me adiciona no LinkedIn:
https://www.linkedin.com/in/marinasgriza-930920?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app

Att. Marina

Em ter., 1 de ago. de 2023 09:25, mauro_fausto ***@***.***>
escreveu:
