### ISSUE TITLE
[Cidade: Taboão da Serra] Pessoa Desenvolvedora Arquiteto .NET SR @dqrtech

### ISSUE THREAD

**Issue by carolinetech** [dotnetdevbr/vagas#859]
## DQR TECH 

Sobre a DQR TECH | Qualidade do começo ao fim

Nascemos de uma parceria de mais de 10 anos entre seus sócios, somando a paixão por tecnologia à vontade de construir uma empresa diferente, investindo na proximidade com nossos parceiros e clientes. Somos uma consultoria especializada em Arquitetura de TI, Outsourcing de Profissionais e Hunting.

## DE ONDE VOCÊ VAI TRABALHAR?
Híbrido 3x na semana em Taboão da Serra.

## O QUE NOS MOVE:
Pessoas & Tecnologia! E é por isso que estamos buscando os melhores profissionais para atuar em nosso cliente do setor público.

## O QUE ESPERAMOS QUE VOCÊ SAIBA:
Experiência na liderança técnica ou arquitetura de soluções em projetos de desenvolvimento de soluções de médio e grande porte. 

Especialista em principais conceitos de desenvolvimento de software (engenharia, qualidade, devsecops e arquitetura). 

.Net Framework; .Net Core; [ASP.Net](http://asp.net/) Web Forms; [ASP.Net](http://asp.net/) MVC. 

Experiência em aplicações Windows Service/BackgroundService. 

Entity Framework. 

Resiliency patterns utilizando [Polly.net](http://polly.net/) 

Windows Server e IIS. 

Experiência em projetos de integração de sistemas. 

Conhecimentos gerais de infraestrutura de TI. 

Arquitetura de Microsserviços

Conhecimento de Twelve-Factor App

Docker, Kubernetes e Openshift

Experiência em desenvolvimento de soluções corporativas e em plataforma Web. 

Experiência em integração de soluções, web services SOAP, REST e demais tecnologias de integração. 

Experiência em projetos .NET implantados como microsserviços em plataforma Docker/Kubernetes/OpenShift. 

Instrumentação e monitoramento de soluções. 

Plataformas de filas e stream: ActiveMQ, Kafka, etc. 

Bases de dados NoSQL: Elasticsearch, MongoDB, Redis, etc. 

Autenticação/autorização utilizando OAuth2 e OpenID Connect 1.0. 

GIT / GIT Flow

CI/CD (com Jenkins ou outras ferramentas). 

Conhecimentos básicos da nuvem Azure e seus produtos. 

QUAIS AS SOFT SKILLS SÃO IMPORTANTES VOCÊ TER:
Saber atuar com autonomia, habilidades de comunicação, boa didática, iniciativa.

## O QUE OFERECEMOS PARA VOCÊ?
Contrato CLT – horário comercial

## Benefícios e Vantagens: 

Plano de Saúde com coparticipação 

Plano Odontológico; 

Seguro de Vida; 

Vale Transporte;

Vale Refeição ou Vale Alimentação 

Todas nossas vagas são destinadas a Pluralidade e Diversidade

**Comment by kerol-barros** [comment]
Vaga imperdível! Vem pra DQR Tech 🧡💙

**Comment by DaianeMFirmiano** [comment]
A vaga pode ser sua!!   Entre em contato com nosso time de recrutamento da DQR TECH!!
