### ISSUE TITLE
[HÍBRIDA NA FARIA LIMA-SP] Fullstack Developer DotNet @DQRTECH

### ISSUE THREAD

**Issue by gsabreudev** [dotnetdevbr/vagas#919]
## Pessoa Desenvolvedora Fullstack .Net core

Sobre a DQR TECH | Qualidade do começo ao fim
Nascemos de uma parceria de mais de 10 anos entre seus sócios, somando a paixão por tecnologia à vontade de construir uma empresa diferente, investindo na proximidade com nossos parceiros e clientes. Somos uma consultoria especializada em Arquitetura de TI, Outsourcing de Profissionais e Hunting.

## DE ONDE VOCÊ VAI TRABALHAR?
3x por semana Híbrido na Faria Lima!

## O QUE NOS MOVE:
Pessoas & Tecnologia! E é por isso que estamos buscando os melhores profissionais para atuar em nosso cliente de setor financeiro.

## O QUE ESPERAMOS QUE VOCÊ SAIBA:

Experiência em projetos de desenvolvimento de software utilizando .NET Core;
Experiência em serviços de mensageria (RabbitMQ/Kafka ou semelhante);
Design Patterns GoF; KISS; YAGNI; DRY
Desenvolvimento de aplicações em nuvem AWS (Lambda, SQS; SNS, DynamoDb, S3, EC2, RDS);
Execução de testes unitários;
Metodologia ágil.

## O QUE SERIA LEGAL SE VOCÊ TIVESSE:

React ou Angular;
Atuação com o mercado financeiro;
Experiência em modelagem de dados em DDD;
Conhecimento em Arquitetura de Microsserviços.

## QUAIS AS SOFT SKILLS SÃO IMPORTANTES VOCÊ TER:
Saber atuar com autonomia, habilidades de comunicação, boa didática, iniciativa.

## O QUE OFERECEMOS PARA VOCÊ?

Auxílio alimentação no cartão Caju;
Assistência médica e odontológica da Porto Seguro e Mediservice, gratuita para você (sem coparticipação ou mensalidade);
Você ainda pode incluir seus dependentes legais com apenas 50% de desconto da mensalidade em folha;
Oferecemos auxílio Psicológico através da PsicologiaViva, estendida para dependentes;
Auxílio creche (segundo as condições vigentes da convenção coletiva do Sindpd-SP);
Seguro de vida da Porto Seguro, em grupo;
Aqui a sua indicação vale premiação de 1K;
No mês do seu aniversário tem presente;
A cada aniversário de DQR Tech, você recebe um mimo;
Notebook para o desempenho das atividades + kit de onboarding da DQR Tech;
Contrato CLT.

##  ENVIE SEU CURRÍCULO OU LINKEDIN PARA: vagas@dqrtech.com.br

![219144236-30eb7da4-46c8-4945-9e67-72612c60b29b](https://github.com/dotnetdevbr/vagas/assets/87737865/5322b433-08c5-4552-a990-d0f1029f64f2)

**Comment by kerol-barros** [comment]
#vemparaDQRTech
