### ISSUE TITLE
(Híbrido/SP) Pessoa Desenvolvedora Fullstack .Net core - DQR TECH

### ISSUE THREAD

**Issue by DaianeMFirmiano** [dotnetdevbr/vagas#935]
Pessoa Desenvolvedora Fullstack .Net core

 3x por semana Híbrido Faria Lima - São Paulo/SP
 Efetivo

Sobre a DQR TECH | Qualidade do começo ao fim
A DQR TECH é uma consultoria parceira dos seus clientes, que possui um ecossistema de serviços, atuando de forma abrangente em todo ciclo de desenvolvimento de software. Desde a concepção e desenvolvimento até a manutenção e sustentação.
Levando soluções aos seus desafios de tecnologia, na forma de Projetos, Outsoucing e Squad.

DE ONDE VOCÊ VAI TRABALHAR?
3x por semana Híbrido na Faria Lima!

O QUE NOS MOVE:
Pessoas & Tecnologia! E é por isso que estamos buscando os melhores profissionais para atuar em nosso cliente de setor financeiro.

O QUE ESPERAMOS QUE VOCÊ SAIBA:
Experiência em projetos de desenvolvimento de software utilizando .NET Core;
Experiência em serviços de mensageria (RabbitMQ/Kafka ou semelhante);
Design Patterns GoF; KISS; YAGNI; DRY
Desenvolvimento de aplicações em nuvem AWS (Lambda, SQS; SNS, DynamoDb, S3, EC2, RDS);
Execução de testes unitários;
React ou Angular;
Metodologia ágil.

O QUE SERIA LEGAL SE VOCÊ TIVESSE:
Atuação com o mercado financeiro;
Experiência em modelagem de dados em DDD;
Conhecimento em Arquitetura de Microsserviços.

QUAIS AS SOFT SKILLS SÃO IMPORTANTES VOCÊ TER:
Saber atuar com autonomia, habilidades de comunicação, boa didática, iniciativa.

O QUE OFERECEMOS PARA VOCÊ?
Auxílio flexível para gastar como quiser (vale alimentação );
Assistência médica e odontológica gratuita para você (sem coparticipação ou mensalidade),
Você ainda pode incluir seus dependentes legais com apenas 50% de desconto da mensalidade em folha;
Oferecemos auxílio Psicológico através da PsicologiaViva, estendida para dependentes;
Auxílio creche (segundo as condições vigentes da convenção coletiva do Sindpd-SP);
Seguro de vida em grupo;
Aqui a sua indicação vale premiação de 1k
No mês do seu aniversário tem mimos;
Notebook para o desempenho das atividades;
Contrato CLT.

Todas nossas vagas são destinadas a Pluralidade e Diversidade.

Enviar seu CV para: vagas@dqrtech.com.br

**Comment by martinhosebastiao** [comment]
Olá bom dia, 

Como e aonde devo enviar a candidatura? Não vejo nenhum email na descrição

**Comment by DaianeMFirmiano** [comment]
Olá!!!
Enviar seu CV para: vagas@dqrtech.com.br
