### ISSUE TITLE
[Remoto] Junior .NET Developer 

### ISSUE THREAD

**Issue by henryzybs** [dotnetdevbr/vagas#978]
## Nossa empresa

Estamos buscando um Desenvolvedor Júnior .NET entusiasta e motivado para se juntar à nossa equipe de desenvolvimento. Se você é um profissional apaixonado por programação e deseja iniciar sua carreira na área de desenvolvimento de software, esta é uma excelente oportunidade para você. Você trabalhará em projetos desafiadores e terá a oportunidade de aprender e crescer em um ambiente colaborativo e dinâmico

## Descrição da vaga

Auxiliar no desenvolvimento, implementação e manutenção de aplicativos .NET.
Escrever código limpo, legível e eficiente em C#.
Colaborar com a equipe para traduzir requisitos de negócios em soluções técnicas.
Realizar testes de unidade e integração para garantir a qualidade do código.
Manter-se atualizado com as melhores práticas de desenvolvimento e tecnologias emergentes.

## Local

Remoto 

## Requisitos

**Obrigatórios:**
**NÃO É REQUISITO A FALA EM INGLÊS APENAS A ESCRITA NO MOMENTO.**
Conhecimento básico de programação orientada a objetos e estruturas de dados.
Familiaridade com a linguagem de programação C# e o framework .NET.
Capacidade de resolver problemas de forma criativa e eficiente.
Excelentes habilidades de comunicação e trabalho em equipe.

**Desejáveis:**
Experiência prévia com desenvolvimento de software, estágios ou projetos acadêmicos.
Conhecimento básico de SQL e bancos de dados relacionais.
Familiaridade com metodologias ágeis de desenvolvimento de software.
Interesse em aprender novas tecnologias e aprimorar suas habilidades de programação.

## Benefícios
Aulas de Inglês
Auxilio estudo
- ...

## Contratação

A combinar

## Como se candidatar

Por favor envie um mensagem no Whatsapp wa.me/5548996356187
Aos cuidados de Fernando da BCI Consultoria

#### Alocação

- Remoto

#### Regime
- CLT
- Estágio
- Freela
- PJ

#### Nível
- Júnior

#### Período
- Full time
- Part time
- Projeto

#### Remuneração
- R$ 1k - R$ 5k
- R$ 5k - R$ 10k

**Comment by gustavros** [comment]
É GOLPE!

**Comment by teixeira-alexandre** [comment]
Golpe.

**Comment by jonathankarlinski** [comment]
GOLPE!!!
