### ISSUE TITLE
[Remoto] Fullstack Developer .Net C# na Coodesh

### ISSUE THREAD

**Issue by FrancieleGhizzoni** [dotnetdevbr/vagas#979]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/jobs/fullstack-developer-net-c-211535470?utm_source=github&utm_medium=dotnetdevbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p><strong>#VemPraTrinks</strong></p>
<p>Aqui você vai fazer parte de um #timaço que tem a missão de revolucionar o mercado da beleza através de soluções digitais completas para estabelecimentos do ramo, que vão desde a gestão do negócio até serviços financeiros, ferramentas de fidelização, agendamento online e muito mais!</p>
<p>Nosso propósito é ajudar a impulsionar esses negócios permitindo que sejam cada vez mais fortes e tenham mais chances de prosperar. Por aqui, ajudamos pessoas a encontrarem e se conectarem a lugares incríveis para aumentar sua autoestima! 🚀</p>
<p>Não faltarão desafios para colocarmos todos os salões do Brasil nos Trinks! 🧡</p>
<p></p>
<p>Se você é apaixonado(a) por desenvolver código de alta qualidade e está ansioso(a) para atuar em um projeto desafiador, esta é a sua oportunidade de brilhar. 🚀</p>
<p></p>
<p><strong>Dá uma olhada no seu papel nessa #revolução:</strong></p>
<p>⇨ Atuar em um produto sólido no mercado e com regras de negócios agradáveis;</p>
<p>⇨ Escrever código limpo, de fácil manutenção, utilizando as melhores práticas de desenvolvimento de software;</p>
<p>⇨ Procurar sempre criar para a Trinks a melhor experiência de uso para o usuário final, trabalhando de perto com os especialistas de UX;</p>
<p>⇨ Atuar com um time de desenvolvedores de qualidade, sendo a referência técnica para o time, orientando e contribuindo para as melhores soluções;</p>
<p>⇨ Estar sempre crescendo e se desenvolvendo tecnicamente e profissionalmente;</p>
<p>⇨ Participar de times geograficamente distribuídos.</p>
<p></p>
<p><strong>O que você precisa para o #match perfeito:</strong></p>
<p>⇨ Domínio em uma ou mais linguagens de programação - aqui você trabalhará com C#;</p>
<p>⇨ Conhecimento em um ou mais frameworks MVVM (AngularJS, VueJS, React e/ou similares);</p>
<p>⇨ Experiência no desenvolvimento de API/Rest de alta escalabilidade;</p>
<p>⇨ Saber aplicar padrões de projeto;</p>
<p>⇨ Conhecer práticas de entrega contínua;</p>
<p>⇨ Domínio de um ou mais banco de dados relacionais;</p>
<p>⇨ Gostar de compartilhar conhecimentos e trabalhar em equipe.</p>
<p></p>
<p><strong>Saca só o que OFERECEMOS:</strong></p>
<p>🏠 100% Home office;</p>
<p>⏳ Contratação CLT (40 horas semanais);</p>
<p>💰 Auxílio home office;</p>
<p>🍴 Vale alimentação e vale refeição no cartão flexível;</p>
<p>🏥 Plano de Saúde SulAmérica (custo zero para o colaborador);</p>
<p>🏥 Plano Odonto Bradesco Saúde (custo zero para o colaborador);</p>
<p>🤸 TotalPass (plano academia);</p>
<p>🎓 Incentivo ao Desenvolvimento: PDI, Capacitações, Feedbacks, Plataforma de Cursos, Desconto com Faculdades e Cursos de Idiomas.</p>
<p>💰 Bônus por indicação de talentos;</p>
<p>🎉 Day off de aniversário e tempo de casa;</p>
<p></p>
<p>♿<strong> Todas as nossas vagas são abertas para pessoas com deficiência.</strong></p>
<p>Na Trinks, valorizamos a melhor versão de você mesmo, com incentivos e autonomia para trabalhar, desenvolver e implementar ideias.</p>
<p>E aí, se identificou? Então vem com a gente impulsionar e conectar os negócios de beleza 🚀🧡</p>
<p></p>
<p><strong>LGPD na Trinks</strong></p>
<p>Você sabia que a Trinks adota uma rigorosa política para garantir o controle e a transparência no tratamento de dados das pessoas que têm interesse em fazer parte do nosso time? Todas as informações e dados obtidos ao longo do processo seletivo são tratados cuidadosamente, em conformidade com as normas da LGPD.</p>
<p>Para mais informações, leia nossa política de dados no: https://materiais.trinks.com/mkt-lgpd-vagas .</p>
## Trinks.com: 
 <p>A Trinks é uma plataforma completa elaborada para Gestão Online de Negócios de Beleza.</p>
<p>Donos de estabelecimentos, redes ou franquias podem administrar e ter domínio sobre todas as frentes, podendo assim, focar no crescimento estratégico do seu negócio.&nbsp;</p><a href='https://coodesh.com/companies/trinks-servicos-de-internet-sa'>Veja mais no site</a>

 ## Habilidades: 
 - .NET 
- C# 
- Angular.js 
- React.js 
- MVVM
## Local: 
 100% Remoto

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Fullstack Developer .Net C# na Trinks.com](https://coodesh.com/jobs/fullstack-developer-net-c-211535470?utm_source=github&utm_medium=dotnetdevbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
CLT
#### Categoria
Full-Stack

**Comment by VictorIgorDev** [comment]
Me candidatei, tomara que eu consiga essa oportunidade de ouro.
